### ISSUE TITLE
Neither 1.12.x nor 1.13.x unit tests build with boost 1.59.0

### ISSUE THREAD

**Issue by CelticMinstrel** [CelticMinstrel/wesnoth#491]
**[Original submission](https://gna.org/bugs/index.php?23897)** by limburgher on 2015-09-22

Build log for 1.12.4 against Fedora rawhide ends with:

g++ -o build/release/tests/main.o -c -std#c++98 -W -O2 -O2 -g -pipe -Wall -Werrorformat-security -fexceptions -fstack-protector-strong --param#ssp-buffer-size4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 

src/tests/main.cpp:98:3: error: expected initializer at end of input

 BOOST_GLOBAL_FIXTURE(wesnoth_global_fixture)

   ^

scons: *** [build/release/tests/main.o] Error 1

scons: building terminated because of errors.

I also tried the most recent git version but it fails for another reason:

Bytecompiling .py files below /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.1-0.fc24git52558d.x86_64/usr/lib/python2.7 using /usr/bin/python2.7

Compiling /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.1-0.fc24git52558d.x86_64/usr/share/wesnoth/data/tools/wesnoth/wmlparser3.py ...

  File "/usr/share/wesnoth/data/tools/wesnoth/wmlparser3.py", line 81

    def __init__(self, data : bytes):

                            ^

SyntaxError: invalid syntax

**Comment by CelticMinstrel** [comment]
**Modified on 2015-09-22**

**anonymous wrote:**

> first issue: 
> 
> seems like a semicolon missing after BOOST_GLOBAL_FIXTURE
> 
> second issue:
> 
> afaik wmlparser3 i meant to be used with python3.
> 
> 
> 
> both the boost tests and the python tools are not necessary to play wesnoth, you should try to disable these things from your build.

**Comment by CelticMinstrel** [comment]
**Modified on 2015-09-23**

**limburgher wrote:**

> That worked, thanks!  Hopefully the tests will be updated sometime in the 1.13.x cycle.

**Comment by CelticMinstrel** [comment]
**Modified on 2015-10-19**

**shadowmaster changed title:** Neither 1.12.x nor 1.13.x builds with boost 1.59.0 -> Neither 1.12.x nor 1.13.x unit tests build with boost 1.59.0

**shadowmaster changed item group:** None of the others -> Unit Tests

**Comment by CelticMinstrel** [comment]
**Modified on 2015-12-30**

**aginor changed status:** None -> Ready For Test

**aginor wrote:**

> This may be fixed by https://gna.org/bugs/?24234
> 
> 
> 
> Could you please re-test?

**Comment by CelticMinstrel** [comment]
**Modified on 2016-01-05**

**limburgher wrote:**

> No, it fails with, for git snapshot starting with f997b4:
> 
> 
> 
> src/tests/utils/auto_parameterized.hpp:75:73: error: no matching function for call to 'make_test_case(void (*)(const test_network::sendfile_param&amp;), boost::unit_test::const_string, test_network::sendfile_param*&amp;, test_network::sendfile_param*&amp;)'
> 
>                BOOST_JOIN(test_name, _begin), BOOST_JOIN(test_name, _end))); \
> 
>                                                                          ^
> 
> src/tests/test_network_worker.cpp:262:1: note: in expansion of macro 'WESNOTH_PARAMETERIZED_TEST_CASE'
> 
>  WESNOTH_PARAMETERIZED_TEST_CASE( test_multi_sendfile, sendfile_param, sendfile_sizes, size )
> 
>  ^
> 
> etc. . . .
> 
> 
> 
> If I disable tests I get a Python error towards the end of the RPM build process:
> 
> 
> 
> Bytecompiling .py files below /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
> 
> Compiling /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py ...
> 
>   File &quot;/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py&quot;, line 18
> 
>     def append_tag(tag : wmlparser.TagNode, sub : str) -&gt; wmlparser.TagNode:
> 
>                        ^
> 
> SyntaxError: invalid syntax

**Comment by CelticMinstrel** [comment]
**Modified on 2016-01-16**

**aginor changed status:** Ready For Test -> Confirmed

**Comment by CelticMinstrel** [comment]
**Modified on 2016-08-08**

**limburgher wrote:**

> I'm still getting the Python error on 1.13.5, can you have a look?  I'd like to update rawhide to 1.13.5 if possible.

**Comment by CelticMinstrel** [comment]
**Modified on 2016-08-09**

**aginor changed status:** Confirmed -> In Progress

**aginor wrote:**

> I'll have a look.
> 
> From the looks of things I'll have to figure out how to build RPMs, which it's been 10+ years since I did the last time so it might take me a little while.
> 
> 
> 
> Have you done any other modifications than to take the spec-file from a previous release and updated?
> 
> 
> 
> Is boost 1.59 still a priority?

**Comment by CelticMinstrel** [comment]
**Modified on 2016-08-09**

**limburgher wrote:**

> Boost is fine, it's just the Python syntax error:
> 
> 
> 
> Bytecompiling .py files below /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
> 
> Compiling /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py ...
> 
> File &quot;/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py&quot;, line 18
> 
> def append_tag(tag : wmlparser.TagNode, sub : str) -&gt; wmlparser.TagNode:
> 
> ^
> 
> SyntaxError: invalid syntax

**Comment by CelticMinstrel** [comment]
**Modified on 2016-08-10**

**shadowmaster wrote:**

> data/tools/wesnoth/campaignserver_client.py is supposed to be run with Python 3 since version 1.13.2, and the log excerpt you posted makes it seem like something in the pipeline is assuming Python 2.
> 
> 
> 
> Perhaps adding a /usr/bin/python3 shebang to it would solve the issue? Note that normally it wouldn't need one since it's not intended to be run on its own, but rather it's imported by data/tools/wesnoth_addon_manager which does have the correct shebang.

**Comment by CelticMinstrel** [comment]
**Modified on 2016-08-10**

**limburgher wrote:**

> Right, the RPM byte compiler assumes Python2.  When I change it to Python3 it discovers other scripts whose syntax is invalid for Python3.  Is the project currently a mix of both 2 and 3?

**Comment by CelticMinstrel** [comment]
**Modified on 2017-04-29**

**aginor changed status:** In Progress -> None
